# Pandas y series de tiempo
## Juan Manuel González Ascencio - A00572003

Importamos las librerias necesarias

In [1]:
import pandas as pd

Leemos el archivo y mostramos las primeras 10 filas

In [8]:
#Abrir el archivo y leerlo
df = pd.read_csv('Summer-Olympic-medals-1976-to-2008.csv', encoding='latin-1')
df.head(10)

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,Montreal,1976.0,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
2,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
3,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
4,Montreal,1976.0,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze
5,Montreal,1976.0,Aquatics,Diving,10m platform,"LOUGANIS, Gregory",Men,USA,United States,M,Silver
6,Montreal,1976.0,Aquatics,Diving,10m platform,"VAYTSEKHOVSKAYA, Elena",Women,URS,Soviet Union,W,Gold
7,Montreal,1976.0,Aquatics,Diving,3m springboard,"POTTER-MCINGVALE, Cynthia",Women,USA,United States,W,Bronze
8,Montreal,1976.0,Aquatics,Diving,10m platform,"DIBIASI, Klaus",Men,ITA,Italy,M,Gold
9,Montreal,1976.0,Aquatics,Diving,10m platform,"ALEINIK, Vladimir",Men,URS,Soviet Union,M,Bronze

cambiamos el formato de la fecha y ponemos hacemos que sea el indice

In [9]:
#construir un objeto de series de tiempo con el índice igual a la fecha de los juegos olímpicos en formato tiempo
df['Date'] = pd.to_datetime(df['Year'], format='%Y')
df.set_index('Date', inplace=True) #el implace es para que se guarde en el mismo dataframe
df.head(10)

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
Date,,,,,,,,,,,
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"LOUGANIS, Gregory",Men,USA,United States,M,Silver
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"VAYTSEKHOVSKAYA, Elena",Women,URS,Soviet Union,W,Gold
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"POTTER-MCINGVALE, Cynthia",Women,USA,United States,W,Bronze
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"DIBIASI, Klaus",Men,ITA,Italy,M,Gold
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"ALEINIK, Vladimir",Men,URS,Soviet Union,M,Bronze

Separar en dos columnas el nombre del atleta

In [11]:
#Separar nombres de apellidos en dos columnas distintas usando la coma como separador
#df['Athlete'] = df['Athlete'].str.split(',', expand=True)
#separar en dos columnas
df[['Surname', 'Name']] = df['Athlete'].str.split(' ', n=1, expand=True)
df.head(10)

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal,Surname,Name
Date,,,,,,,,,,,,,
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver,"KÖHLER,",Christa
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze,"KOSENKOV,",Aleksandr
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold,"BOGGS,",Philip George
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver,"CAGNOTTO,",Giorgio Franco
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze,"WILSON,",Deborah Keplar
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"LOUGANIS, Gregory",Men,USA,United States,M,Silver,"LOUGANIS,",Gregory
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"VAYTSEKHOVSKAYA, Elena",Women,URS,Soviet Union,W,Gold,"VAYTSEKHOVSKAYA,",Elena
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"POTTER-MCINGVALE, Cynthia",Women,USA,United States,W,Bronze,"POTTER-MCINGVALE,",Cynthia
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"DIBIASI, Klaus",Men,ITA,Italy,M,Gold,"DIBIASI,",Klaus
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"ALEINIK, Vladimir",Men,URS,Soviet Union,M,Bronze,"ALEINIK,",Vladimir

Obtener medidas resumen del conjunto de datos. Cuál es el país que ganó más medallas?

In [12]:

#Obtener medidas resumen del conjunto de datos. Cuál es el país que ganó más medallas?
df.describe(include='all')
df['Country'].value_counts().idxmax()

'United States'

Construir una tabla que muestre cuántas medallas obtuvieron los hombres en total en cada año que se realizó el evento

In [21]:
#si el Event-gender es m agregar a un nuevo dataframe
dfm = df.loc[df['Event_gender'] == 'M']
dfm.head(10)

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal,Surname,Name
Date,,,,,,,,,,,,,
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze,"KOSENKOV,",Aleksandr
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold,"BOGGS,",Philip George
1976-01-01,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver,"CAGNOTTO,",Giorgio Franco
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"LOUGANIS, Gregory",Men,USA,United States,M,Silver,"LOUGANIS,",Gregory
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"DIBIASI, Klaus",Men,ITA,Italy,M,Gold,"DIBIASI,",Klaus
1976-01-01,Montreal,1976.0,Aquatics,Diving,10m platform,"ALEINIK, Vladimir",Men,URS,Soviet Union,M,Bronze,"ALEINIK,",Vladimir
1976-01-01,Montreal,1976.0,Aquatics,Swimming,400m freestyle,"SHAW, Timothy Andrew",Men,USA,United States,M,Silver,"SHAW,",Timothy Andrew
1976-01-01,Montreal,1976.0,Aquatics,Swimming,1500m freestyle,"HOLLAND, Stephen",Men,AUS,Australia,M,Bronze,"HOLLAND,",Stephen
1976-01-01,Montreal,1976.0,Aquatics,Swimming,400m individual medley,"SMIRNOV, Andrei",Men,URS,Soviet Union,M,Bronze,"SMIRNOV,",Andrei
1976-01-01,Montreal,1976.0,Aquatics,Swimming,200m backstroke,"ROCCA, Peter Drake",Men,USA,United States,M,Silver,"ROCCA,",Peter Drake