# juan manuel gonzalez ascencio - a00572003
# quiz1 - manipulaci√≥n y lectura usando pandas

impotamos las librerias necesarias

In [8]:
import pandas as pd
import json

leemos el archivo json llamado DatosPractica-1.json

In [12]:
df = open('DatosPractica-1.json')
data = json.load(df)
data

{'columns': ['nombre',
  'categoria',
  'existencia',
  'precioCompra',
  'precioVenta',
  'ventaDiariaPromedio'],
 'index': ['DFG',
  'ESC',
  'FBD',
  'QWE',
  'RVF',
  'UJM',
  'IOP',
  'LJH',
  'GFT',
  'RDF',
  'TGS',
  'TRE',
  'VSD',
  'ASD',
  'AQW',
  'CDE',
  'SDF',
  'JHG',
  'FRD',
  'RTD',
  'TYH',
  'TRD',
  'TRO',
  'HYU'],
 'data': [['Lapiz', 'Escritura', 80, 5.0, 6.45, 46],
  ['Borrador', 'Pizarron', 60, 20.0, 22.6, 82],
  ['Goma', 'Escritura', 55, 10.0, 12.4, 67],
  ['Marcador Permanente Negro', 'Escritura', 45, 35.0, 42.0, 37],
  ['Corrector', 'Escritura', 34, 18.0, 19.44, 12],
  ['Boligrafo Azul', 'Escritura', 46, 5.0, 5.55, 50],
  ['Boligrafo Rojo', 'Escritura', 75, 5.0, 5.9, 96],
  ['Marcador Permanente Azul', 'Escritura', 36, 35.0, 38.15, 21],
  ['Marcador Permanente Rojo', 'Escritura', 54, 35.0, 40.25, 36],
  ['Sacapuntas', 'Escritura', 45, 20.0, 23.4, 42],
  ['Juego De Geometria', 'Dibujo', 65, 55.0, 69.3, 38],
  ['Lapiz De Dibujo H2', 'Dibujo', 32, 23.0, 29.44, 6],
  ['Regla 60Cm', 'Dibujo', 48, 30.0, 33.3, 70],
  ['Colores Prismacolor', 'Dibujo', 76, 150.0, 163.5, 32],
  ['Colores Fantasy', 'Dibujo', 28, 130.0, 159.9, 14],
  ['Hoja Blanca Carta', 'Papel', 36, 40.0, 49.6, 18],
  ['Hoja Blanca Oficio', 'Papel', 29, 50.0, 53.0, 15],
  ['Portaminas', 'Escritura', 64, 76.0, 95.76, 82],
  ['Tijeras', 'Dibujo', 75, 45.0, 47.7, 37],
  ['Plumon Rojo', 'Pizarron', 65, 28.0, 36.12, 33],
  ['Plumon Azul', 'Pizarron', 45, 28.0, 32.2, 22],
  ['Plumon Negro', 'Pizarron', 47, 28.0, 36.4, 50],
  ['Calcomanias', 'Otro', 100, 10.0, 12.3, 26],
  ['Clips', 'Otro', 70, 16.0, 16.8, 40]]}

ahora lo leemos con pandas para poder explorarlo de mejor manera

In [60]:
df = pd.read_json('DatosPractica-1.json', orient='split')
df

,nombre,categoria,existencia,precioCompra,precioVenta,ventaDiariaPromedio
DFG,Lapiz,Escritura,80,5,6.45,46
ESC,Borrador,Pizarron,60,20,22.60,82
FBD,Goma,Escritura,55,10,12.40,67
QWE,Marcador Permanente Negro,Escritura,45,35,42.00,37
RVF,Corrector,Escritura,34,18,19.44,12
UJM,Boligrafo Azul,Escritura,46,5,5.55,50
IOP,Boligrafo Rojo,Escritura,75,5,5.90,96
LJH,Marcador Permanente Azul,Escritura,36,35,38.15,21
GFT,Marcador Permanente Rojo,Escritura,54,35,40.25,36
RDF,Sacapuntas,Escritura,45,20,23.40,42
TGS,Juego De Geometria,Dibujo,65,55,69.30,38
TRE,Lapiz De Dibujo H2,Dibujo,32,23,29.44,6
VSD,Regla 60Cm,Dibujo,48,30,33.30,70
ASD,Colores Prismacolor,Dibujo,76,150,163.50,32
AQW,Colores Fantasy,Dibujo,28,130,159.90,14
CDE,Hoja Blanca Carta,Papel,36,40,49.60,18
SDF,Hoja Blanca Oficio,Papel,29,50,53.00,15
JHG,Portaminas,Escritura,64,76,95.76,82
FRD,Tijeras,Dibujo,75,45,47.70,37
RTD,Plumon Rojo,Pizarron,65,28,36.12,33
TYH,Plumon Azul,Pizarron,45,28,32.20,22
TRD,Plumon Negro,Pizarron,47,28,36.40,50
TRO,Calcomanias,Otro,100,10,12.30,26
HYU,Clips,Otro,70,16,16.80,40

Se not√≥ que se cometieron algunos errores al momento de capturar los datos de los productos, por lo que es necesario realizar las siguientes correcciones (en orden):

1. Despliega la columna nombre y existencias de las claves JHG, TRE y TRO de modo que veas el siguiente resultado.

In [89]:
df = pd.read_json('DatosPractica-1.json', orient='split')

df = df.loc[['JHG', 'TRE', 'TRO']]

df = df[['nombre', 'existencia']]
df

                 nombre  existencia
JHG          Portaminas          64
TRE  Lapiz De Dibujo H2          32
TRO         Calcomanias         100

Sustituye en los nombres de columnas/filas

El √≠ndice ‚ÄòJHG‚Äô por ‚ÄòHJG‚Äô
La columna ‚Äònombre‚Äô por ‚ÄòProducto‚Äô
 

Pega aqu√≠ los comandos utilizados para estos cambios y su despliegue para confirmar los cambios:

In [91]:
# cambia el nombre del indice jhg por hjg
df = df.rename(index={'JHG':' HJG'})
df = df.rename(columns={'nombre':'producto'})
df

                producto  existencia
 HJG          Portaminas          64
TRE   Lapiz De Dibujo H2          32
TRO          Calcomanias         100

3. Sustituye en los valores

El nombre correcto del producto del √≠ndice ‚ÄòTRE‚Äô es ‚ÄòLapiz H2‚Äô
Solo se tienen 50 calcoman√≠as (√≠ndice ‚ÄòTRO‚Äô)
 

Pega aqu√≠ los comandos utilizados para estos cambios y su despliegue para confirmar los cambios:

In [92]:
df.loc['TRE', 'producto'] = 'Lapiz H2'
df.loc['TRO', 'existencia'] = 50
df

         producto  existencia
 HJG   Portaminas          64
TRE      Lapiz H2          32
TRO   Calcomanias          50

agregamos una nueva columna llamada GananciaUnidad que contenga el resultado de restar el precio de venta menos el precio de compra

In [ ]:
df2 = pd.read_json('DatosPractica-1.json', orient='split')
df2

In [98]:
df2['GananciaUnidad'] = df2['precioVenta'] - df2['precioCompra']
df2['GananciaUnidad'].sum()

154.46

agregamos una nueva columna llamada IngresoTotal que calcule el ingreso  en caso de que se venda toda la existencia del producto

In [99]:

df2['IngresoTotal'] = df2['GananciaUnidad'] * df2['existencia']
df2['IngresoTotal'].sum()

7865.18

agregamos una nueva columna de tipo booleano, la cual se llame BajoInventario y que marque true si la existencia es menor a 40

In [101]:
df2['BajoInventario'] = df2['existencia'] < 40
df2['BajoInventario'].sum()
df2

,nombre,categoria,existencia,precioCompra,precioVenta,ventaDiariaPromedio,GananciaUnidad,IngresoTotal,BajoInventario
DFG,Lapiz,Escritura,80,5,6.45,46,1.45,116.00,False
ESC,Borrador,Pizarron,60,20,22.60,82,2.60,156.00,False
FBD,Goma,Escritura,55,10,12.40,67,2.40,132.00,False
QWE,Marcador Permanente Negro,Escritura,45,35,42.00,37,7.00,315.00,False
RVF,Corrector,Escritura,34,18,19.44,12,1.44,48.96,True
UJM,Boligrafo Azul,Escritura,46,5,5.55,50,0.55,25.30,False
IOP,Boligrafo Rojo,Escritura,75,5,5.90,96,0.90,67.50,False
LJH,Marcador Permanente Azul,Escritura,36,35,38.15,21,3.15,113.40,True
GFT,Marcador Permanente Rojo,Escritura,54,35,40.25,36,5.25,283.50,False
RDF,Sacapuntas,Escritura,45,20,23.40,42,3.40,153.00,False
TGS,Juego De Geometria,Dibujo,65,55,69.30,38,14.30,929.50,False
TRE,Lapiz De Dibujo H2,Dibujo,32,23,29.44,6,6.44,206.08,True
VSD,Regla 60Cm,Dibujo,48,30,33.30,70,3.30,158.40,False
ASD,Colores Prismacolor,Dibujo,76,150,163.50,32,13.50,1026.00,False
AQW,Colores Fantasy,Dibujo,28,130,159.90,14,29.90,837.20,True
CDE,Hoja Blanca Carta,Papel,36,40,49.60,18,9.60,345.60,True
SDF,Hoja Blanca Oficio,Papel,29,50,53.00,15,3.00,87.00,True
JHG,Portaminas,Escritura,64,76,95.76,82,19.76,1264.64,False
FRD,Tijeras,Dibujo,75,45,47.70,37,2.70,202.50,False
RTD,Plumon Rojo,Pizarron,65,28,36.12,33,8.12,527.80,False
TYH,Plumon Azul,Pizarron,45,28,32.20,22,4.20,189.00,False
TRD,Plumon Negro,Pizarron,47,28,36.40,50,8.40,394.80,False
TRO,Calcomanias,Otro,100,10,12.30,26,2.30,230.00,False
HYU,Clips,Otro,70,16,16.80,40,0.80,56.00,False

agregamos una nueva columa llamada fecha_alta que contenga el primer dia de cada mes consecutivo a partir de mi fecha de nacimiento, la cuale el 3/12/2001

In [102]:
df['fecha_alta'] = pd.date_range('2002-01-01', periods=24, freq='MS')
df

ValueError: Length of values (24) does not match length of index (3)

obtenemos los siguientes datos
* el total de productos en exitencia
* ganancia por unidad maxima
* el promedio de precio de vente 
* el total de ingresos en caso de que se venda todo el inventario

In [79]:
df['existencia'].sum()
df['GananciaUnidad'].max()
df['precioVenta'].mean()
df['IngresoTotal'].sum()

7865.18

obtenemos el total de productos de las siguientes categr√≠as.
* dibujo
* escritura 
* pizarron
* papel
* otros

In [87]:
#calcula el total de productos de categor√≠a dibujo
df.loc[df['categoria'] == 'Dibujo'].count()
df.loc[df['categoria'] == 'Escritura'].count()
df.loc[df['categoria'] == 'Pizarron'].count()
df.loc[df['categoria'] == 'Papel'].count()
df.loc[df['categoria'] == 'Otro'].count()

nombre                 2
categoria              2
existencia             2
precioCompra           2
precioVenta            2
ventaDiariaPromedio    2
GananciaUnidad         2
IngresoTotal           2
BajoInventario         2
fecha_alta             2
dtype: int64

In [95]:
df.to_csv('DatosPractica-1.csv', sep='|', index=False)

AttributeError: 'DataFrame' object has no attribute 'read_csv'

exportamos el dataframe a html

In [ ]:
%%shell
jupyter nbconvert --to html /content/Pandas+Gonzalez_Ascencio.ipynb